version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

networks:
  default:
    driver: bridge
