version: '3.8'

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    ports:
      - "8384:8384"       # Web GUI
      - "22000:22000"     # Sync traffic
      - "21027:21027/udp" # Local discovery
    volumes:
      - ./syncthing/config:/var/syncthing/config
      - /mnt/ssd/backup:/mnt/backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    networks:
      - syncthing-net

networks:
  syncthing-net:
    driver: bridge
