services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./conf.yml:/app/user-data/conf.yml # Corrected path
    restart: always
